server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pogreb
    username: admin
    password: admin
  jpa:
    generate-ddl: true

logging:
  level:
    root: INFO # Уровень логгирования для всех логгеров
    ru.karen: DEBUG
  file:
    name: nod.log # Имя файла для записи логов
    path: ./ # Путь к директории, где будет создан файл
    max-file-size: 50MB
    max-history: 10
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" # Шаблон для вывода логов в консоль
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" # Шаблон для записи логов в файл


